APP_NAME = "Pressure Control Console"

BAUD_RATE = 115200
HANDSHAKE_TIMEOUT_MS = 4000
HANDSHAKE_RETRY_INTERVAL_MS = 500
HEARTBEAT_INTERVAL_MS = 500
HEARTBEAT_TIMEOUT_MS = 2000
DATA_INTERVAL_MS = 100
GRAPH_WINDOW_SECONDS = 10.0
PARSE_ERROR_LIMIT = 3

ADC_MAX = 1023
MAX_VOLTAGE = 5.0
MAX_PRESSURE_BAR = 10.0

SIMULATOR_PORT = "SIMULATOR"
DEFAULT_FQBN = "arduino:avr:uno"
FIRMWARE_VERSION = "1.0.0"
